// Code generated by ent, DO NOT EDIT.

package checkinlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldEQ(FieldUserID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldEQ(FieldAmount, v))
}

// ConsecutiveDays applies equality check predicate on the "consecutive_days" field. It's identical to ConsecutiveDaysEQ.
func ConsecutiveDays(v int) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldEQ(FieldConsecutiveDays, v))
}

// CheckinDate applies equality check predicate on the "checkin_date" field. It's identical to CheckinDateEQ.
func CheckinDate(v time.Time) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldEQ(FieldCheckinDate, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldNotIn(FieldUserID, vs...))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldLTE(FieldAmount, v))
}

// ConsecutiveDaysEQ applies the EQ predicate on the "consecutive_days" field.
func ConsecutiveDaysEQ(v int) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldEQ(FieldConsecutiveDays, v))
}

// ConsecutiveDaysNEQ applies the NEQ predicate on the "consecutive_days" field.
func ConsecutiveDaysNEQ(v int) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldNEQ(FieldConsecutiveDays, v))
}

// ConsecutiveDaysIn applies the In predicate on the "consecutive_days" field.
func ConsecutiveDaysIn(vs ...int) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldIn(FieldConsecutiveDays, vs...))
}

// ConsecutiveDaysNotIn applies the NotIn predicate on the "consecutive_days" field.
func ConsecutiveDaysNotIn(vs ...int) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldNotIn(FieldConsecutiveDays, vs...))
}

// ConsecutiveDaysGT applies the GT predicate on the "consecutive_days" field.
func ConsecutiveDaysGT(v int) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldGT(FieldConsecutiveDays, v))
}

// ConsecutiveDaysGTE applies the GTE predicate on the "consecutive_days" field.
func ConsecutiveDaysGTE(v int) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldGTE(FieldConsecutiveDays, v))
}

// ConsecutiveDaysLT applies the LT predicate on the "consecutive_days" field.
func ConsecutiveDaysLT(v int) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldLT(FieldConsecutiveDays, v))
}

// ConsecutiveDaysLTE applies the LTE predicate on the "consecutive_days" field.
func ConsecutiveDaysLTE(v int) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldLTE(FieldConsecutiveDays, v))
}

// CheckinDateEQ applies the EQ predicate on the "checkin_date" field.
func CheckinDateEQ(v time.Time) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldEQ(FieldCheckinDate, v))
}

// CheckinDateNEQ applies the NEQ predicate on the "checkin_date" field.
func CheckinDateNEQ(v time.Time) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldNEQ(FieldCheckinDate, v))
}

// CheckinDateIn applies the In predicate on the "checkin_date" field.
func CheckinDateIn(vs ...time.Time) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldIn(FieldCheckinDate, vs...))
}

// CheckinDateNotIn applies the NotIn predicate on the "checkin_date" field.
func CheckinDateNotIn(vs ...time.Time) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldNotIn(FieldCheckinDate, vs...))
}

// CheckinDateGT applies the GT predicate on the "checkin_date" field.
func CheckinDateGT(v time.Time) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldGT(FieldCheckinDate, v))
}

// CheckinDateGTE applies the GTE predicate on the "checkin_date" field.
func CheckinDateGTE(v time.Time) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldGTE(FieldCheckinDate, v))
}

// CheckinDateLT applies the LT predicate on the "checkin_date" field.
func CheckinDateLT(v time.Time) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldLT(FieldCheckinDate, v))
}

// CheckinDateLTE applies the LTE predicate on the "checkin_date" field.
func CheckinDateLTE(v time.Time) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldLTE(FieldCheckinDate, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CheckinLog {
	return predicate.CheckinLog(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.CheckinLog {
	return predicate.CheckinLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.CheckinLog {
	return predicate.CheckinLog(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CheckinLog) predicate.CheckinLog {
	return predicate.CheckinLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CheckinLog) predicate.CheckinLog {
	return predicate.CheckinLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CheckinLog) predicate.CheckinLog {
	return predicate.CheckinLog(sql.NotPredicates(p))
}
