// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/checkinlog"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CheckinLogUpdate is the builder for updating CheckinLog entities.
type CheckinLogUpdate struct {
	config
	hooks    []Hook
	mutation *CheckinLogMutation
}

// Where appends a list predicates to the CheckinLogUpdate builder.
func (_u *CheckinLogUpdate) Where(ps ...predicate.CheckinLog) *CheckinLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CheckinLogUpdate) SetUserID(v int64) *CheckinLogUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CheckinLogUpdate) SetNillableUserID(v *int64) *CheckinLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *CheckinLogUpdate) SetAmount(v float64) *CheckinLogUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *CheckinLogUpdate) SetNillableAmount(v *float64) *CheckinLogUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *CheckinLogUpdate) AddAmount(v float64) *CheckinLogUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetConsecutiveDays sets the "consecutive_days" field.
func (_u *CheckinLogUpdate) SetConsecutiveDays(v int) *CheckinLogUpdate {
	_u.mutation.ResetConsecutiveDays()
	_u.mutation.SetConsecutiveDays(v)
	return _u
}

// SetNillableConsecutiveDays sets the "consecutive_days" field if the given value is not nil.
func (_u *CheckinLogUpdate) SetNillableConsecutiveDays(v *int) *CheckinLogUpdate {
	if v != nil {
		_u.SetConsecutiveDays(*v)
	}
	return _u
}

// AddConsecutiveDays adds value to the "consecutive_days" field.
func (_u *CheckinLogUpdate) AddConsecutiveDays(v int) *CheckinLogUpdate {
	_u.mutation.AddConsecutiveDays(v)
	return _u
}

// SetCheckinDate sets the "checkin_date" field.
func (_u *CheckinLogUpdate) SetCheckinDate(v time.Time) *CheckinLogUpdate {
	_u.mutation.SetCheckinDate(v)
	return _u
}

// SetNillableCheckinDate sets the "checkin_date" field if the given value is not nil.
func (_u *CheckinLogUpdate) SetNillableCheckinDate(v *time.Time) *CheckinLogUpdate {
	if v != nil {
		_u.SetCheckinDate(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CheckinLogUpdate) SetUser(v *User) *CheckinLogUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the CheckinLogMutation object of the builder.
func (_u *CheckinLogUpdate) Mutation() *CheckinLogMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CheckinLogUpdate) ClearUser() *CheckinLogUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CheckinLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckinLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CheckinLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckinLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CheckinLogUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CheckinLog.user"`)
	}
	return nil
}

func (_u *CheckinLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkinlog.Table, checkinlog.Columns, sqlgraph.NewFieldSpec(checkinlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(checkinlog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(checkinlog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ConsecutiveDays(); ok {
		_spec.SetField(checkinlog.FieldConsecutiveDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveDays(); ok {
		_spec.AddField(checkinlog.FieldConsecutiveDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CheckinDate(); ok {
		_spec.SetField(checkinlog.FieldCheckinDate, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkinlog.UserTable,
			Columns: []string{checkinlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkinlog.UserTable,
			Columns: []string{checkinlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkinlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CheckinLogUpdateOne is the builder for updating a single CheckinLog entity.
type CheckinLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CheckinLogMutation
}

// SetUserID sets the "user_id" field.
func (_u *CheckinLogUpdateOne) SetUserID(v int64) *CheckinLogUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CheckinLogUpdateOne) SetNillableUserID(v *int64) *CheckinLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *CheckinLogUpdateOne) SetAmount(v float64) *CheckinLogUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *CheckinLogUpdateOne) SetNillableAmount(v *float64) *CheckinLogUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *CheckinLogUpdateOne) AddAmount(v float64) *CheckinLogUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetConsecutiveDays sets the "consecutive_days" field.
func (_u *CheckinLogUpdateOne) SetConsecutiveDays(v int) *CheckinLogUpdateOne {
	_u.mutation.ResetConsecutiveDays()
	_u.mutation.SetConsecutiveDays(v)
	return _u
}

// SetNillableConsecutiveDays sets the "consecutive_days" field if the given value is not nil.
func (_u *CheckinLogUpdateOne) SetNillableConsecutiveDays(v *int) *CheckinLogUpdateOne {
	if v != nil {
		_u.SetConsecutiveDays(*v)
	}
	return _u
}

// AddConsecutiveDays adds value to the "consecutive_days" field.
func (_u *CheckinLogUpdateOne) AddConsecutiveDays(v int) *CheckinLogUpdateOne {
	_u.mutation.AddConsecutiveDays(v)
	return _u
}

// SetCheckinDate sets the "checkin_date" field.
func (_u *CheckinLogUpdateOne) SetCheckinDate(v time.Time) *CheckinLogUpdateOne {
	_u.mutation.SetCheckinDate(v)
	return _u
}

// SetNillableCheckinDate sets the "checkin_date" field if the given value is not nil.
func (_u *CheckinLogUpdateOne) SetNillableCheckinDate(v *time.Time) *CheckinLogUpdateOne {
	if v != nil {
		_u.SetCheckinDate(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CheckinLogUpdateOne) SetUser(v *User) *CheckinLogUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the CheckinLogMutation object of the builder.
func (_u *CheckinLogUpdateOne) Mutation() *CheckinLogMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CheckinLogUpdateOne) ClearUser() *CheckinLogUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the CheckinLogUpdate builder.
func (_u *CheckinLogUpdateOne) Where(ps ...predicate.CheckinLog) *CheckinLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CheckinLogUpdateOne) Select(field string, fields ...string) *CheckinLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CheckinLog entity.
func (_u *CheckinLogUpdateOne) Save(ctx context.Context) (*CheckinLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CheckinLogUpdateOne) SaveX(ctx context.Context) *CheckinLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CheckinLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CheckinLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CheckinLogUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CheckinLog.user"`)
	}
	return nil
}

func (_u *CheckinLogUpdateOne) sqlSave(ctx context.Context) (_node *CheckinLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(checkinlog.Table, checkinlog.Columns, sqlgraph.NewFieldSpec(checkinlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CheckinLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, checkinlog.FieldID)
		for _, f := range fields {
			if !checkinlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != checkinlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(checkinlog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(checkinlog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ConsecutiveDays(); ok {
		_spec.SetField(checkinlog.FieldConsecutiveDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveDays(); ok {
		_spec.AddField(checkinlog.FieldConsecutiveDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CheckinDate(); ok {
		_spec.SetField(checkinlog.FieldCheckinDate, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkinlog.UserTable,
			Columns: []string{checkinlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkinlog.UserTable,
			Columns: []string{checkinlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CheckinLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{checkinlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
