// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/checkinlog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CheckinLog is the model entity for the CheckinLog schema.
type CheckinLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// ConsecutiveDays holds the value of the "consecutive_days" field.
	ConsecutiveDays int `json:"consecutive_days,omitempty"`
	// CheckinDate holds the value of the "checkin_date" field.
	CheckinDate time.Time `json:"checkin_date,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CheckinLogQuery when eager-loading is set.
	Edges        CheckinLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CheckinLogEdges holds the relations/edges for other nodes in the graph.
type CheckinLogEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CheckinLogEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CheckinLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case checkinlog.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case checkinlog.FieldID, checkinlog.FieldUserID, checkinlog.FieldConsecutiveDays:
			values[i] = new(sql.NullInt64)
		case checkinlog.FieldCheckinDate, checkinlog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CheckinLog fields.
func (_m *CheckinLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case checkinlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case checkinlog.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case checkinlog.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case checkinlog.FieldConsecutiveDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consecutive_days", values[i])
			} else if value.Valid {
				_m.ConsecutiveDays = int(value.Int64)
			}
		case checkinlog.FieldCheckinDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field checkin_date", values[i])
			} else if value.Valid {
				_m.CheckinDate = value.Time
			}
		case checkinlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CheckinLog.
// This includes values selected through modifiers, order, etc.
func (_m *CheckinLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the CheckinLog entity.
func (_m *CheckinLog) QueryUser() *UserQuery {
	return NewCheckinLogClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this CheckinLog.
// Note that you need to call CheckinLog.Unwrap() before calling this method if this CheckinLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CheckinLog) Update() *CheckinLogUpdateOne {
	return NewCheckinLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CheckinLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CheckinLog) Unwrap() *CheckinLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CheckinLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CheckinLog) String() string {
	var builder strings.Builder
	builder.WriteString("CheckinLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("consecutive_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConsecutiveDays))
	builder.WriteString(", ")
	builder.WriteString("checkin_date=")
	builder.WriteString(_m.CheckinDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CheckinLogs is a parsable slice of CheckinLog.
type CheckinLogs []*CheckinLog
