// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/checkinlog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CheckinLogCreate is the builder for creating a CheckinLog entity.
type CheckinLogCreate struct {
	config
	mutation *CheckinLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *CheckinLogCreate) SetUserID(v int64) *CheckinLogCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *CheckinLogCreate) SetAmount(v float64) *CheckinLogCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetConsecutiveDays sets the "consecutive_days" field.
func (_c *CheckinLogCreate) SetConsecutiveDays(v int) *CheckinLogCreate {
	_c.mutation.SetConsecutiveDays(v)
	return _c
}

// SetNillableConsecutiveDays sets the "consecutive_days" field if the given value is not nil.
func (_c *CheckinLogCreate) SetNillableConsecutiveDays(v *int) *CheckinLogCreate {
	if v != nil {
		_c.SetConsecutiveDays(*v)
	}
	return _c
}

// SetCheckinDate sets the "checkin_date" field.
func (_c *CheckinLogCreate) SetCheckinDate(v time.Time) *CheckinLogCreate {
	_c.mutation.SetCheckinDate(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CheckinLogCreate) SetCreatedAt(v time.Time) *CheckinLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CheckinLogCreate) SetNillableCreatedAt(v *time.Time) *CheckinLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *CheckinLogCreate) SetUser(v *User) *CheckinLogCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the CheckinLogMutation object of the builder.
func (_c *CheckinLogCreate) Mutation() *CheckinLogMutation {
	return _c.mutation
}

// Save creates the CheckinLog in the database.
func (_c *CheckinLogCreate) Save(ctx context.Context) (*CheckinLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CheckinLogCreate) SaveX(ctx context.Context) *CheckinLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CheckinLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CheckinLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CheckinLogCreate) defaults() {
	if _, ok := _c.mutation.ConsecutiveDays(); !ok {
		v := checkinlog.DefaultConsecutiveDays
		_c.mutation.SetConsecutiveDays(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := checkinlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CheckinLogCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CheckinLog.user_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "CheckinLog.amount"`)}
	}
	if _, ok := _c.mutation.ConsecutiveDays(); !ok {
		return &ValidationError{Name: "consecutive_days", err: errors.New(`ent: missing required field "CheckinLog.consecutive_days"`)}
	}
	if _, ok := _c.mutation.CheckinDate(); !ok {
		return &ValidationError{Name: "checkin_date", err: errors.New(`ent: missing required field "CheckinLog.checkin_date"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CheckinLog.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "CheckinLog.user"`)}
	}
	return nil
}

func (_c *CheckinLogCreate) sqlSave(ctx context.Context) (*CheckinLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CheckinLogCreate) createSpec() (*CheckinLog, *sqlgraph.CreateSpec) {
	var (
		_node = &CheckinLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(checkinlog.Table, sqlgraph.NewFieldSpec(checkinlog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(checkinlog.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.ConsecutiveDays(); ok {
		_spec.SetField(checkinlog.FieldConsecutiveDays, field.TypeInt, value)
		_node.ConsecutiveDays = value
	}
	if value, ok := _c.mutation.CheckinDate(); ok {
		_spec.SetField(checkinlog.FieldCheckinDate, field.TypeTime, value)
		_node.CheckinDate = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(checkinlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   checkinlog.UserTable,
			Columns: []string{checkinlog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CheckinLog.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CheckinLogUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *CheckinLogCreate) OnConflict(opts ...sql.ConflictOption) *CheckinLogUpsertOne {
	_c.conflict = opts
	return &CheckinLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CheckinLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CheckinLogCreate) OnConflictColumns(columns ...string) *CheckinLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CheckinLogUpsertOne{
		create: _c,
	}
}

type (
	// CheckinLogUpsertOne is the builder for "upsert"-ing
	//  one CheckinLog node.
	CheckinLogUpsertOne struct {
		create *CheckinLogCreate
	}

	// CheckinLogUpsert is the "OnConflict" setter.
	CheckinLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *CheckinLogUpsert) SetUserID(v int64) *CheckinLogUpsert {
	u.Set(checkinlog.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CheckinLogUpsert) UpdateUserID() *CheckinLogUpsert {
	u.SetExcluded(checkinlog.FieldUserID)
	return u
}

// SetAmount sets the "amount" field.
func (u *CheckinLogUpsert) SetAmount(v float64) *CheckinLogUpsert {
	u.Set(checkinlog.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CheckinLogUpsert) UpdateAmount() *CheckinLogUpsert {
	u.SetExcluded(checkinlog.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *CheckinLogUpsert) AddAmount(v float64) *CheckinLogUpsert {
	u.Add(checkinlog.FieldAmount, v)
	return u
}

// SetConsecutiveDays sets the "consecutive_days" field.
func (u *CheckinLogUpsert) SetConsecutiveDays(v int) *CheckinLogUpsert {
	u.Set(checkinlog.FieldConsecutiveDays, v)
	return u
}

// UpdateConsecutiveDays sets the "consecutive_days" field to the value that was provided on create.
func (u *CheckinLogUpsert) UpdateConsecutiveDays() *CheckinLogUpsert {
	u.SetExcluded(checkinlog.FieldConsecutiveDays)
	return u
}

// AddConsecutiveDays adds v to the "consecutive_days" field.
func (u *CheckinLogUpsert) AddConsecutiveDays(v int) *CheckinLogUpsert {
	u.Add(checkinlog.FieldConsecutiveDays, v)
	return u
}

// SetCheckinDate sets the "checkin_date" field.
func (u *CheckinLogUpsert) SetCheckinDate(v time.Time) *CheckinLogUpsert {
	u.Set(checkinlog.FieldCheckinDate, v)
	return u
}

// UpdateCheckinDate sets the "checkin_date" field to the value that was provided on create.
func (u *CheckinLogUpsert) UpdateCheckinDate() *CheckinLogUpsert {
	u.SetExcluded(checkinlog.FieldCheckinDate)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CheckinLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CheckinLogUpsertOne) UpdateNewValues() *CheckinLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(checkinlog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CheckinLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CheckinLogUpsertOne) Ignore() *CheckinLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CheckinLogUpsertOne) DoNothing() *CheckinLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CheckinLogCreate.OnConflict
// documentation for more info.
func (u *CheckinLogUpsertOne) Update(set func(*CheckinLogUpsert)) *CheckinLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CheckinLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *CheckinLogUpsertOne) SetUserID(v int64) *CheckinLogUpsertOne {
	return u.Update(func(s *CheckinLogUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CheckinLogUpsertOne) UpdateUserID() *CheckinLogUpsertOne {
	return u.Update(func(s *CheckinLogUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *CheckinLogUpsertOne) SetAmount(v float64) *CheckinLogUpsertOne {
	return u.Update(func(s *CheckinLogUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *CheckinLogUpsertOne) AddAmount(v float64) *CheckinLogUpsertOne {
	return u.Update(func(s *CheckinLogUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CheckinLogUpsertOne) UpdateAmount() *CheckinLogUpsertOne {
	return u.Update(func(s *CheckinLogUpsert) {
		s.UpdateAmount()
	})
}

// SetConsecutiveDays sets the "consecutive_days" field.
func (u *CheckinLogUpsertOne) SetConsecutiveDays(v int) *CheckinLogUpsertOne {
	return u.Update(func(s *CheckinLogUpsert) {
		s.SetConsecutiveDays(v)
	})
}

// AddConsecutiveDays adds v to the "consecutive_days" field.
func (u *CheckinLogUpsertOne) AddConsecutiveDays(v int) *CheckinLogUpsertOne {
	return u.Update(func(s *CheckinLogUpsert) {
		s.AddConsecutiveDays(v)
	})
}

// UpdateConsecutiveDays sets the "consecutive_days" field to the value that was provided on create.
func (u *CheckinLogUpsertOne) UpdateConsecutiveDays() *CheckinLogUpsertOne {
	return u.Update(func(s *CheckinLogUpsert) {
		s.UpdateConsecutiveDays()
	})
}

// SetCheckinDate sets the "checkin_date" field.
func (u *CheckinLogUpsertOne) SetCheckinDate(v time.Time) *CheckinLogUpsertOne {
	return u.Update(func(s *CheckinLogUpsert) {
		s.SetCheckinDate(v)
	})
}

// UpdateCheckinDate sets the "checkin_date" field to the value that was provided on create.
func (u *CheckinLogUpsertOne) UpdateCheckinDate() *CheckinLogUpsertOne {
	return u.Update(func(s *CheckinLogUpsert) {
		s.UpdateCheckinDate()
	})
}

// Exec executes the query.
func (u *CheckinLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CheckinLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CheckinLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CheckinLogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CheckinLogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CheckinLogCreateBulk is the builder for creating many CheckinLog entities in bulk.
type CheckinLogCreateBulk struct {
	config
	err      error
	builders []*CheckinLogCreate
	conflict []sql.ConflictOption
}

// Save creates the CheckinLog entities in the database.
func (_c *CheckinLogCreateBulk) Save(ctx context.Context) ([]*CheckinLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CheckinLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CheckinLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CheckinLogCreateBulk) SaveX(ctx context.Context) []*CheckinLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CheckinLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CheckinLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CheckinLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CheckinLogUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *CheckinLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *CheckinLogUpsertBulk {
	_c.conflict = opts
	return &CheckinLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CheckinLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CheckinLogCreateBulk) OnConflictColumns(columns ...string) *CheckinLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CheckinLogUpsertBulk{
		create: _c,
	}
}

// CheckinLogUpsertBulk is the builder for "upsert"-ing
// a bulk of CheckinLog nodes.
type CheckinLogUpsertBulk struct {
	create *CheckinLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CheckinLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CheckinLogUpsertBulk) UpdateNewValues() *CheckinLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(checkinlog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CheckinLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CheckinLogUpsertBulk) Ignore() *CheckinLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CheckinLogUpsertBulk) DoNothing() *CheckinLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CheckinLogCreateBulk.OnConflict
// documentation for more info.
func (u *CheckinLogUpsertBulk) Update(set func(*CheckinLogUpsert)) *CheckinLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CheckinLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *CheckinLogUpsertBulk) SetUserID(v int64) *CheckinLogUpsertBulk {
	return u.Update(func(s *CheckinLogUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CheckinLogUpsertBulk) UpdateUserID() *CheckinLogUpsertBulk {
	return u.Update(func(s *CheckinLogUpsert) {
		s.UpdateUserID()
	})
}

// SetAmount sets the "amount" field.
func (u *CheckinLogUpsertBulk) SetAmount(v float64) *CheckinLogUpsertBulk {
	return u.Update(func(s *CheckinLogUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *CheckinLogUpsertBulk) AddAmount(v float64) *CheckinLogUpsertBulk {
	return u.Update(func(s *CheckinLogUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CheckinLogUpsertBulk) UpdateAmount() *CheckinLogUpsertBulk {
	return u.Update(func(s *CheckinLogUpsert) {
		s.UpdateAmount()
	})
}

// SetConsecutiveDays sets the "consecutive_days" field.
func (u *CheckinLogUpsertBulk) SetConsecutiveDays(v int) *CheckinLogUpsertBulk {
	return u.Update(func(s *CheckinLogUpsert) {
		s.SetConsecutiveDays(v)
	})
}

// AddConsecutiveDays adds v to the "consecutive_days" field.
func (u *CheckinLogUpsertBulk) AddConsecutiveDays(v int) *CheckinLogUpsertBulk {
	return u.Update(func(s *CheckinLogUpsert) {
		s.AddConsecutiveDays(v)
	})
}

// UpdateConsecutiveDays sets the "consecutive_days" field to the value that was provided on create.
func (u *CheckinLogUpsertBulk) UpdateConsecutiveDays() *CheckinLogUpsertBulk {
	return u.Update(func(s *CheckinLogUpsert) {
		s.UpdateConsecutiveDays()
	})
}

// SetCheckinDate sets the "checkin_date" field.
func (u *CheckinLogUpsertBulk) SetCheckinDate(v time.Time) *CheckinLogUpsertBulk {
	return u.Update(func(s *CheckinLogUpsert) {
		s.SetCheckinDate(v)
	})
}

// UpdateCheckinDate sets the "checkin_date" field to the value that was provided on create.
func (u *CheckinLogUpsertBulk) UpdateCheckinDate() *CheckinLogUpsertBulk {
	return u.Update(func(s *CheckinLogUpsert) {
		s.UpdateCheckinDate()
	})
}

// Exec executes the query.
func (u *CheckinLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CheckinLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CheckinLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CheckinLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
